//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhDev.SharePoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RhDev_SharePoint {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RhDev_SharePoint() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RhDev.SharePoint.Resources.RhDev.SharePoint", typeof(RhDev_SharePoint).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Záznam konfigurace.
        /// </summary>
        internal static string ContentTypesConfigurationDescription {
            get {
                return ResourceManager.GetString("ContentTypesConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Záznam konfigurace.
        /// </summary>
        internal static string ContentTypesConfigurationTitle {
            get {
                return ResourceManager.GetString("ContentTypesConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Záznam svátku.
        /// </summary>
        internal static string ContentTypesDayOffDescription {
            get {
                return ResourceManager.GetString("ContentTypesDayOffDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Záznam svátku.
        /// </summary>
        internal static string ContentTypesDayOffTitle {
            get {
                return ResourceManager.GetString("ContentTypesDayOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev společné.
        /// </summary>
        internal static string ContentTypesGroup {
            get {
                return ResourceManager.GetString("ContentTypesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Záznam logu.
        /// </summary>
        internal static string ContentTypesLogDescription {
            get {
                return ResourceManager.GetString("ContentTypesLogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Záznam logu.
        /// </summary>
        internal static string ContentTypesLogTitle {
            get {
                return ResourceManager.GetString("ContentTypesLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace logger installation for solution monitoring.
        /// </summary>
        internal static string FeatureFarmDescription {
            get {
                return ResourceManager.GetString("FeatureFarmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev Common.
        /// </summary>
        internal static string FeatureFarmTitle {
            get {
                return ResourceManager.GetString("FeatureFarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsahuje definice sloupců a typů obsahů pro jednotné řešení RhDev.
        /// </summary>
        internal static string FeatureSiteDescription {
            get {
                return ResourceManager.GetString("FeatureSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev společné.
        /// </summary>
        internal static string FeatureSiteTitle {
            get {
                return ResourceManager.GetString("FeatureSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsahuje definice seznamů pro jednotné řešení RhDev.
        /// </summary>
        internal static string FeatureWebDescription {
            get {
                return ResourceManager.GetString("FeatureWebDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev společné.
        /// </summary>
        internal static string FeatureWebTitle {
            get {
                return ResourceManager.GetString("FeatureWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klíč.
        /// </summary>
        internal static string FieldsConfigKey {
            get {
                return ResourceManager.GetString("FieldsConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul.
        /// </summary>
        internal static string FieldsConfigModule {
            get {
                return ResourceManager.GetString("FieldsConfigModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota.
        /// </summary>
        internal static string FieldsConfigValue {
            get {
                return ResourceManager.GetString("FieldsConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string FieldsDayOffDate {
            get {
                return ResourceManager.GetString("FieldsDayOffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCID.
        /// </summary>
        internal static string FieldsDayOffLcid {
            get {
                return ResourceManager.GetString("FieldsDayOffLcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opakuje se každoročně.
        /// </summary>
        internal static string FieldsDayOffRepeat {
            get {
                return ResourceManager.GetString("FieldsDayOffRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev společné.
        /// </summary>
        internal static string FieldsGroup {
            get {
                return ResourceManager.GetString("FieldsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        internal static string FieldsLogDate {
            get {
                return ResourceManager.GetString("FieldsLogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úroveň.
        /// </summary>
        internal static string FieldsLogLevel {
            get {
                return ResourceManager.GetString("FieldsLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpráva.
        /// </summary>
        internal static string FieldsLogMessage {
            get {
                return ResourceManager.GetString("FieldsLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdroj.
        /// </summary>
        internal static string FieldsLogSource {
            get {
                return ResourceManager.GetString("FieldsLogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsahuje konfiguraci aplikace.
        /// </summary>
        internal static string ListsConfigurationDescription {
            get {
                return ResourceManager.GetString("ListsConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurace aplikace.
        /// </summary>
        internal static string ListsConfigurationTitle {
            get {
                return ResourceManager.GetString("ListsConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsahuje státní svátky.
        /// </summary>
        internal static string ListsDayOffDescription {
            get {
                return ResourceManager.GetString("ListsDayOffDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RhDev státní svátky.
        /// </summary>
        internal static string ListsDayOffTitle {
            get {
                return ResourceManager.GetString("ListsDayOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsahuje logování aplikace.
        /// </summary>
        internal static string ListsLogDescription {
            get {
                return ResourceManager.GetString("ListsLogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikační log.
        /// </summary>
        internal static string ListsLogTitle {
            get {
                return ResourceManager.GetString("ListsLogTitle", resourceCulture);
            }
        }
    }
}
